name: DiscordWhitelistManager
version: ${project.version}
main: net.mcpueblo.discordwhitelistmanager.DiscordWhitelistManager
api-version: 1.13
load: STARTUP
depend: [DiscordSRV]
authors: [JuanDelPueblo]
description: Simple plugin to remove whitelist and unlink on guild leave.
website: https://mcpueblo.net
